# -*- coding: utf-8 -*-
"""bmi-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcexzbs_Z6PoPELAWfp1Huyn3sP7c7GG
"""

name = input("Enter your name: ")

try:
    weight = float(input("Weight (kg): "))
    height_cm = float(input("Height (cm): "))
    height_m = height_cm / 100

    if weight <= 0 or height_m <= 0:
        print("Values must be positive.")
    else:
        bmi = round(weight / (height_m ** 2), 1)

        if bmi < 18.5:
            category = "Underweight"
        elif bmi < 25:
            category = "Normal"
        elif bmi < 30:
            category = "Overweight"
        else:
            category = "Obese"

        print(f"{name}, your BMI is {bmi} → {category}")
except ValueError:
    print("Please enter numbers only.")

result = f"Weight: {weight} kg\nHeight: {height_cm} cm\nBMI: {bmi}\nCategory: {category}\n"

with open("bmi_results.txt", "w") as file:
    file.write(result)

print("Results saved to bmi_results.txt")